version: 2
updates:
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "monthly"
    time: "02:00"
    timezone: "Asia/Tokyo"
  reviewers:
    - "Kotaro-Shibata"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
    time: "02:00"
    timezone: Asia/Tokyo
  reviewers:
    - "Kotaro-Shibata"
